# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiRobot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupSend = QtWidgets.QGroupBox(self.centralwidget)
        self.groupSend.setGeometry(QtCore.QRect(0, 100, 400, 500))
        self.groupSend.setObjectName("groupSend")
        self.label = QtWidgets.QLabel(self.groupSend)
        self.label.setGeometry(QtCore.QRect(10, 20, 58, 16))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.groupSend)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 400, 340))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAuto = QtWidgets.QWidget()
        self.tabAuto.setObjectName("tabAuto")
        self.labelForward = QtWidgets.QLabel(self.tabAuto)
        self.labelForward.setGeometry(QtCore.QRect(15, 10, 60, 20))
        self.labelForward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForward.setObjectName("labelForward")
        self.sliderForwardBackward = QtWidgets.QSlider(self.tabAuto)
        self.sliderForwardBackward.setGeometry(QtCore.QRect(30, 30, 30, 230))
        self.sliderForwardBackward.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.sliderForwardBackward.setMinimum(-100)
        self.sliderForwardBackward.setMaximum(100)
        self.sliderForwardBackward.setOrientation(QtCore.Qt.Vertical)
        self.sliderForwardBackward.setObjectName("sliderForwardBackward")
        self.spinBoxForwardBackward = QtWidgets.QSpinBox(self.tabAuto)
        self.spinBoxForwardBackward.setGeometry(QtCore.QRect(20, 280, 50, 25))
        self.spinBoxForwardBackward.setMinimum(-100)
        self.spinBoxForwardBackward.setMaximum(100)
        self.spinBoxForwardBackward.setSingleStep(2)
        self.spinBoxForwardBackward.setProperty("value", 0)
        self.spinBoxForwardBackward.setObjectName("spinBoxForwardBackward")
        self.labelBackward = QtWidgets.QLabel(self.tabAuto)
        self.labelBackward.setGeometry(QtCore.QRect(15, 260, 60, 20))
        self.labelBackward.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBackward.setObjectName("labelBackward")
        self.buttonResetForwardBackward = QtWidgets.QPushButton(self.tabAuto)
        self.buttonResetForwardBackward.setGeometry(QtCore.QRect(65, 95, 28, 93))
        self.buttonResetForwardBackward.setObjectName("buttonResetForwardBackward")
        self.sliderLeftRight = QtWidgets.QSlider(self.tabAuto)
        self.sliderLeftRight.setGeometry(QtCore.QRect(140, 240, 200, 30))
        self.sliderLeftRight.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.sliderLeftRight.setMinimum(-100)
        self.sliderLeftRight.setMaximum(100)
        self.sliderLeftRight.setOrientation(QtCore.Qt.Horizontal)
        self.sliderLeftRight.setObjectName("sliderLeftRight")
        self.spinBoxLeftRight = QtWidgets.QSpinBox(self.tabAuto)
        self.spinBoxLeftRight.setGeometry(QtCore.QRect(185, 280, 50, 25))
        self.spinBoxLeftRight.setMinimum(-100)
        self.spinBoxLeftRight.setMaximum(100)
        self.spinBoxLeftRight.setSingleStep(2)
        self.spinBoxLeftRight.setProperty("value", 0)
        self.spinBoxLeftRight.setObjectName("spinBoxLeftRight")
        self.labelLeft_2 = QtWidgets.QLabel(self.tabAuto)
        self.labelLeft_2.setGeometry(QtCore.QRect(100, 240, 40, 20))
        self.labelLeft_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeft_2.setObjectName("labelLeft_2")
        self.buttonResetLeftRight = QtWidgets.QPushButton(self.tabAuto)
        self.buttonResetLeftRight.setGeometry(QtCore.QRect(245, 280, 93, 28))
        self.buttonResetLeftRight.setObjectName("buttonResetLeftRight")
        self.labelRight_2 = QtWidgets.QLabel(self.tabAuto)
        self.labelRight_2.setGeometry(QtCore.QRect(345, 240, 40, 20))
        self.labelRight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRight_2.setObjectName("labelRight_2")
        self.tabWidget.addTab(self.tabAuto, "")
        self.tabManual = QtWidgets.QWidget()
        self.tabManual.setObjectName("tabManual")
        self.labelRightEngine = QtWidgets.QLabel(self.tabManual)
        self.labelRightEngine.setGeometry(QtCore.QRect(150, 10, 80, 20))
        self.labelRightEngine.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRightEngine.setObjectName("labelRightEngine")
        self.spinBoxLeftEngine = QtWidgets.QSpinBox(self.tabManual)
        self.spinBoxLeftEngine.setGeometry(QtCore.QRect(65, 240, 50, 25))
        self.spinBoxLeftEngine.setMinimum(-128)
        self.spinBoxLeftEngine.setMaximum(127)
        self.spinBoxLeftEngine.setObjectName("spinBoxLeftEngine")
        self.spinBoxRightEngine = QtWidgets.QSpinBox(self.tabManual)
        self.spinBoxRightEngine.setGeometry(QtCore.QRect(165, 240, 50, 25))
        self.spinBoxRightEngine.setMinimum(-128)
        self.spinBoxRightEngine.setMaximum(127)
        self.spinBoxRightEngine.setObjectName("spinBoxRightEngine")
        self.sliderRightEngine = QtWidgets.QSlider(self.tabManual)
        self.sliderRightEngine.setGeometry(QtCore.QRect(175, 30, 30, 200))
        self.sliderRightEngine.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.sliderRightEngine.setMinimum(-128)
        self.sliderRightEngine.setMaximum(127)
        self.sliderRightEngine.setSliderPosition(0)
        self.sliderRightEngine.setOrientation(QtCore.Qt.Vertical)
        self.sliderRightEngine.setObjectName("sliderRightEngine")
        self.labelLeftEngine = QtWidgets.QLabel(self.tabManual)
        self.labelLeftEngine.setGeometry(QtCore.QRect(50, 10, 80, 20))
        self.labelLeftEngine.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeftEngine.setObjectName("labelLeftEngine")
        self.sliderLeftEngine = QtWidgets.QSlider(self.tabManual)
        self.sliderLeftEngine.setGeometry(QtCore.QRect(75, 30, 30, 200))
        self.sliderLeftEngine.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.sliderLeftEngine.setMinimum(-128)
        self.sliderLeftEngine.setMaximum(127)
        self.sliderLeftEngine.setOrientation(QtCore.Qt.Vertical)
        self.sliderLeftEngine.setObjectName("sliderLeftEngine")
        self.buttonResetLeft = QtWidgets.QPushButton(self.tabManual)
        self.buttonResetLeft.setGeometry(QtCore.QRect(50, 280, 80, 28))
        self.buttonResetLeft.setObjectName("buttonResetLeft")
        self.buttonResetRight = QtWidgets.QPushButton(self.tabManual)
        self.buttonResetRight.setGeometry(QtCore.QRect(150, 280, 80, 28))
        self.buttonResetRight.setObjectName("buttonResetRight")
        self.tabWidget.addTab(self.tabManual, "")
        self.tabFrame = QtWidgets.QWidget()
        self.tabFrame.setEnabled(True)
        self.tabFrame.setObjectName("tabFrame")
        self.textManualFrame = QtWidgets.QLineEdit(self.tabFrame)
        self.textManualFrame.setGeometry(QtCore.QRect(60, 15, 80, 20))
        self.textManualFrame.setMaxLength(6)
        self.textManualFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.textManualFrame.setObjectName("textManualFrame")
        self.labelFrameSend_2 = QtWidgets.QLabel(self.tabFrame)
        self.labelFrameSend_2.setGeometry(QtCore.QRect(10, 15, 60, 20))
        self.labelFrameSend_2.setObjectName("labelFrameSend_2")
        self.buttonSaveFrame = QtWidgets.QPushButton(self.tabFrame)
        self.buttonSaveFrame.setGeometry(QtCore.QRect(160, 10, 93, 28))
        self.buttonSaveFrame.setObjectName("buttonSaveFrame")
        self.labelManualFrame = QtWidgets.QLabel(self.tabFrame)
        self.labelManualFrame.setGeometry(QtCore.QRect(10, 100, 371, 81))
        self.labelManualFrame.setText("")
        self.labelManualFrame.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelManualFrame.setObjectName("labelManualFrame")
        self.tabWidget.addTab(self.tabFrame, "")
        self.labelFrameSend = QtWidgets.QLabel(self.groupSend)
        self.labelFrameSend.setGeometry(QtCore.QRect(55, 20, 70, 16))
        self.labelFrameSend.setObjectName("labelFrameSend")
        self.checkBoxLED1 = QtWidgets.QCheckBox(self.groupSend)
        self.checkBoxLED1.setGeometry(QtCore.QRect(270, 80, 60, 20))
        self.checkBoxLED1.setObjectName("checkBoxLED1")
        self.checkBoxLED2 = QtWidgets.QCheckBox(self.groupSend)
        self.checkBoxLED2.setGeometry(QtCore.QRect(330, 80, 60, 20))
        self.checkBoxLED2.setObjectName("checkBoxLED2")
        self.label_2 = QtWidgets.QLabel(self.groupSend)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 100, 16))
        self.label_2.setObjectName("label_2")
        self.labelLastFrameSend = QtWidgets.QLabel(self.groupSend)
        self.labelLastFrameSend.setGeometry(QtCore.QRect(230, 20, 70, 16))
        self.labelLastFrameSend.setObjectName("labelLastFrameSend")
        self.groupBox = QtWidgets.QGroupBox(self.groupSend)
        self.groupBox.setGeometry(QtCore.QRect(0, 380, 401, 121))
        self.groupBox.setObjectName("groupBox")
        self.comboRoboty = QtWidgets.QComboBox(self.groupBox)
        self.comboRoboty.setGeometry(QtCore.QRect(10, 20, 250, 30))
        self.comboRoboty.setObjectName("comboRoboty")
        self.comboRoboty.addItem("")
        self.comboRoboty.addItem("")
        self.buttonDeleteRobot = QtWidgets.QPushButton(self.groupBox)
        self.buttonDeleteRobot.setGeometry(QtCore.QRect(280, 20, 100, 30))
        self.buttonDeleteRobot.setObjectName("buttonDeleteRobot")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 75, 20))
        self.label_5.setObjectName("label_5")
        self.labelIP = QtWidgets.QLabel(self.groupBox)
        self.labelIP.setGeometry(QtCore.QRect(90, 60, 120, 20))
        self.labelIP.setText("")
        self.labelIP.setObjectName("labelIP")
        self.groupReceive = QtWidgets.QGroupBox(self.centralwidget)
        self.groupReceive.setGeometry(QtCore.QRect(400, 100, 400, 500))
        self.groupReceive.setObjectName("groupReceive")
        self.labelFrameReceived = QtWidgets.QLabel(self.groupReceive)
        self.labelFrameReceived.setGeometry(QtCore.QRect(55, 20, 340, 20))
        self.labelFrameReceived.setObjectName("labelFrameReceived")
        self.labelFrameSend_3 = QtWidgets.QLabel(self.groupReceive)
        self.labelFrameSend_3.setGeometry(QtCore.QRect(10, 20, 58, 20))
        self.labelFrameSend_3.setObjectName("labelFrameSend_3")
        self.label_3 = QtWidgets.QLabel(self.groupReceive)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 45, 20))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelStatus = QtWidgets.QLabel(self.groupReceive)
        self.labelStatus.setGeometry(QtCore.QRect(60, 50, 30, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelStatus.setFont(font)
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.progressBarBateria = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarBateria.setGeometry(QtCore.QRect(150, 50, 180, 20))
        self.progressBarBateria.setProperty("value", 0)
        self.progressBarBateria.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.progressBarBateria.setTextVisible(True)
        self.progressBarBateria.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarBateria.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarBateria.setObjectName("progressBarBateria")
        self.label_4 = QtWidgets.QLabel(self.groupReceive)
        self.label_4.setGeometry(QtCore.QRect(100, 50, 55, 20))
        self.label_4.setObjectName("label_4")
        self.progressBarCzujnik1 = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarCzujnik1.setGeometry(QtCore.QRect(15, 100, 50, 300))
        self.progressBarCzujnik1.setMaximum(2000)
        self.progressBarCzujnik1.setProperty("value", 0)
        self.progressBarCzujnik1.setTextVisible(False)
        self.progressBarCzujnik1.setOrientation(QtCore.Qt.Vertical)
        self.progressBarCzujnik1.setObjectName("progressBarCzujnik1")
        self.progressBarCzujnik2 = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarCzujnik2.setGeometry(QtCore.QRect(95, 100, 50, 300))
        self.progressBarCzujnik2.setMaximum(2000)
        self.progressBarCzujnik2.setProperty("value", 0)
        self.progressBarCzujnik2.setTextVisible(False)
        self.progressBarCzujnik2.setOrientation(QtCore.Qt.Vertical)
        self.progressBarCzujnik2.setObjectName("progressBarCzujnik2")
        self.progressBarCzujnik4 = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarCzujnik4.setGeometry(QtCore.QRect(255, 100, 50, 300))
        self.progressBarCzujnik4.setMaximum(2000)
        self.progressBarCzujnik4.setProperty("value", 0)
        self.progressBarCzujnik4.setTextVisible(False)
        self.progressBarCzujnik4.setOrientation(QtCore.Qt.Vertical)
        self.progressBarCzujnik4.setObjectName("progressBarCzujnik4")
        self.progressBarCzujnik5 = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarCzujnik5.setGeometry(QtCore.QRect(335, 100, 50, 300))
        self.progressBarCzujnik5.setMaximum(2000)
        self.progressBarCzujnik5.setProperty("value", 0)
        self.progressBarCzujnik5.setTextVisible(False)
        self.progressBarCzujnik5.setOrientation(QtCore.Qt.Vertical)
        self.progressBarCzujnik5.setObjectName("progressBarCzujnik5")
        self.progressBarCzujnik3 = QtWidgets.QProgressBar(self.groupReceive)
        self.progressBarCzujnik3.setGeometry(QtCore.QRect(175, 100, 50, 300))
        self.progressBarCzujnik3.setMaximum(2000)
        self.progressBarCzujnik3.setProperty("value", 0)
        self.progressBarCzujnik3.setTextVisible(False)
        self.progressBarCzujnik3.setOrientation(QtCore.Qt.Vertical)
        self.progressBarCzujnik3.setObjectName("progressBarCzujnik3")
        self.labelCzujnik1 = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik1.setGeometry(QtCore.QRect(15, 410, 50, 16))
        self.labelCzujnik1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik1.setObjectName("labelCzujnik1")
        self.labelCzujnik2 = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik2.setGeometry(QtCore.QRect(95, 410, 50, 16))
        self.labelCzujnik2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik2.setObjectName("labelCzujnik2")
        self.labelCzujnik3 = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik3.setGeometry(QtCore.QRect(175, 410, 50, 16))
        self.labelCzujnik3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik3.setObjectName("labelCzujnik3")
        self.labelCzujnik4 = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik4.setGeometry(QtCore.QRect(255, 410, 50, 16))
        self.labelCzujnik4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik4.setObjectName("labelCzujnik4")
        self.labelCzujnik5 = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik5.setGeometry(QtCore.QRect(335, 410, 50, 16))
        self.labelCzujnik5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik5.setObjectName("labelCzujnik5")
        self.labelCzujnik1Procent = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik1Procent.setGeometry(QtCore.QRect(15, 430, 50, 16))
        self.labelCzujnik1Procent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik1Procent.setObjectName("labelCzujnik1Procent")
        self.labelCzujnik4Procent = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik4Procent.setGeometry(QtCore.QRect(255, 430, 50, 16))
        self.labelCzujnik4Procent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik4Procent.setObjectName("labelCzujnik4Procent")
        self.labelCzujnik5Procent = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik5Procent.setGeometry(QtCore.QRect(335, 430, 50, 16))
        self.labelCzujnik5Procent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik5Procent.setObjectName("labelCzujnik5Procent")
        self.labelCzujnik2Procent = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik2Procent.setGeometry(QtCore.QRect(95, 430, 50, 16))
        self.labelCzujnik2Procent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik2Procent.setObjectName("labelCzujnik2Procent")
        self.labelCzujnik3Procent = QtWidgets.QLabel(self.groupReceive)
        self.labelCzujnik3Procent.setGeometry(QtCore.QRect(175, 430, 50, 16))
        self.labelCzujnik3Procent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCzujnik3Procent.setObjectName("labelCzujnik3Procent")
        self.labelBateria = QtWidgets.QLabel(self.groupReceive)
        self.labelBateria.setGeometry(QtCore.QRect(340, 50, 60, 20))
        self.labelBateria.setObjectName("labelBateria")
        self.groupConnection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupConnection.setGeometry(QtCore.QRect(0, 0, 801, 100))
        self.groupConnection.setObjectName("groupConnection")
        self.labeip = QtWidgets.QLabel(self.groupConnection)
        self.labeip.setGeometry(QtCore.QRect(10, 20, 70, 16))
        self.labeip.setObjectName("labeip")
        self.txtIPaddress = QtWidgets.QLineEdit(self.groupConnection)
        self.txtIPaddress.setGeometry(QtCore.QRect(80, 20, 120, 20))
        self.txtIPaddress.setAlignment(QtCore.Qt.AlignCenter)
        self.txtIPaddress.setObjectName("txtIPaddress")
        self.buttonConnect = QtWidgets.QPushButton(self.groupConnection)
        self.buttonConnect.setGeometry(QtCore.QRect(210, 15, 93, 28))
        self.buttonConnect.setObjectName("buttonConnect")
        self.buttonDisconnect = QtWidgets.QPushButton(self.groupConnection)
        self.buttonDisconnect.setGeometry(QtCore.QRect(320, 15, 93, 28))
        self.buttonDisconnect.setObjectName("buttonDisconnect")
        self.labelConnect = QtWidgets.QLabel(self.groupConnection)
        self.labelConnect.setGeometry(QtCore.QRect(10, 50, 200, 30))
        self.labelConnect.setText("")
        self.labelConnect.setObjectName("labelConnect")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupConnection)
        self.groupBox_2.setGeometry(QtCore.QRect(620, 0, 181, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioStop = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioStop.setGeometry(QtCore.QRect(110, 70, 130, 20))
        self.radioStop.setChecked(True)
        self.radioStop.setObjectName("radioStop")
        self.radioStart = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioStart.setGeometry(QtCore.QRect(110, 10, 130, 20))
        self.radioStart.setObjectName("radioStart")
        self.radioManual = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioManual.setGeometry(QtCore.QRect(110, 40, 130, 20))
        self.radioManual.setObjectName("radioManual")
        self.buttonManualSend = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonManualSend.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.buttonManualSend.setObjectName("buttonManualSend")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupSend.setTitle(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "Frame:"))
        self.labelForward.setText(_translate("MainWindow", "Forward"))
        self.labelBackward.setText(_translate("MainWindow", "Backward"))
        self.buttonResetForwardBackward.setText(_translate("MainWindow", "R\n"
"e\n"
"s\n"
"e\n"
"t"))
        self.labelLeft_2.setText(_translate("MainWindow", "Left"))
        self.buttonResetLeftRight.setText(_translate("MainWindow", "Reset"))
        self.labelRight_2.setText(_translate("MainWindow", "Right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAuto), _translate("MainWindow", "Auto"))
        self.labelRightEngine.setText(_translate("MainWindow", "RightEngine"))
        self.labelLeftEngine.setText(_translate("MainWindow", "LeftEngine"))
        self.buttonResetLeft.setText(_translate("MainWindow", "Reset"))
        self.buttonResetRight.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabManual), _translate("MainWindow", "Manual"))
        self.textManualFrame.setText(_translate("MainWindow", "000000"))
        self.labelFrameSend_2.setText(_translate("MainWindow", "Frame:"))
        self.buttonSaveFrame.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFrame), _translate("MainWindow", "Frame"))
        self.labelFrameSend.setText(_translate("MainWindow", "[000000]"))
        self.checkBoxLED1.setText(_translate("MainWindow", "LED1"))
        self.checkBoxLED2.setText(_translate("MainWindow", "LED2"))
        self.label_2.setText(_translate("MainWindow", "Last send frame:"))
        self.labelLastFrameSend.setText(_translate("MainWindow", "[000000]"))
        self.groupBox.setTitle(_translate("MainWindow", "Robots"))
        self.comboRoboty.setItemText(0, _translate("MainWindow", "robot1"))
        self.comboRoboty.setItemText(1, _translate("MainWindow", "<nowy>"))
        self.buttonDeleteRobot.setText(_translate("MainWindow", "Remove robot"))
        self.label_5.setText(_translate("MainWindow", "Aktualne IP:"))
        self.groupReceive.setTitle(_translate("MainWindow", "Receive"))
        self.labelFrameReceived.setText(_translate("MainWindow", "[00000000000000000000000000]"))
        self.labelFrameSend_3.setText(_translate("MainWindow", "Frame:"))
        self.label_3.setText(_translate("MainWindow", "Status:"))
        self.label_4.setText(_translate("MainWindow", "Battery:"))
        self.labelCzujnik1.setText(_translate("MainWindow", "0"))
        self.labelCzujnik2.setText(_translate("MainWindow", "0"))
        self.labelCzujnik3.setText(_translate("MainWindow", "0"))
        self.labelCzujnik4.setText(_translate("MainWindow", "0"))
        self.labelCzujnik5.setText(_translate("MainWindow", "0"))
        self.labelCzujnik1Procent.setText(_translate("MainWindow", "0%"))
        self.labelCzujnik4Procent.setText(_translate("MainWindow", "0%"))
        self.labelCzujnik5Procent.setText(_translate("MainWindow", "0%"))
        self.labelCzujnik2Procent.setText(_translate("MainWindow", "0%"))
        self.labelCzujnik3Procent.setText(_translate("MainWindow", "0%"))
        self.labelBateria.setText(_translate("MainWindow", "0mV"))
        self.groupConnection.setTitle(_translate("MainWindow", "Connection"))
        self.labeip.setText(_translate("MainWindow", "IP address:"))
        self.txtIPaddress.setText(_translate("MainWindow", "127.0.0.1"))
        self.buttonConnect.setText(_translate("MainWindow", "Connect"))
        self.buttonDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Send"))
        self.radioStop.setText(_translate("MainWindow", "Stop"))
        self.radioStart.setText(_translate("MainWindow", "Auto"))
        self.radioManual.setText(_translate("MainWindow", "Manual"))
        self.buttonManualSend.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

